import type { Sprite } from '../../src/cat/sprite';

// awake_sit: 0 rest, 1 blink, 2 tail sway.
// Legend: . transparent, k outline, w white, s shade, b brown, d dark brown, p pink, z sleep glyph.
export const AWAKE_SIT: Sprite = {
  id: 'awake_sit',
  fps: 5,
  sequence: [0, 0, 0, 0, 1, 0, 0, 2, 2, 0],
  frames: [
    // frame 0
    [
      '................................',
      '.......k................k.......',
      '......kbk..............kbk......',
      '......kbbkk..........kkbbk......',
      '......kbbbbkkkkkkkkkkbbbbk......',
      '......kbbpbbbbwddwwwbbpbbk......',
      '......kbbppbbbwddwbbbppbbk......',
      '......kbbpbbbbwwwwwwbbpbbk......',
      '......kbbbbbwwwwwwwwwbbbbk......',
      '......kbbbbbwwwwwwwwwwwbbk......',
      '......kbwwwwwwwwwwwwwwwwbk......',
      '......kwwwwwwwwwwwwwwwwwwk......',
      '......kwwwkkwwwwwwwwkkwwwk......',
      '......kwwwkkwwwwwwwwkkwwwk......',
      '......kwwwwwwwwppwwwwwwwwk......',
      '.......kppwwwwkwwkwwwwppk.......',
      '........kwwwwwwkkwwwwwwk.k......',
      '.........kwwwwwwwwwwwwk.kbkk....',
      '..........kkwwwwwwwwkk.kbbbbk...',
      '...........kwwwwwwwwk...kbbbk...',
      '..........kwwsssssswwk...kbbk...',
      '.........kwwwwwwwwwwwwk..kbbbk..',
      '........kwwwwwwwwwwwwwwk.kbbbk..',
      '.......kwwwwwwwwwwwwwwwwkkbbbk..',
      '.......kwbbbwwwwwwwwwwwwkkbbbk..',
      '.......kbbbbbwwwwwwwwwwwkkbbk...',
      '.......kbbbbbkwwwwkwwwwwkbbbk...',
      '........kbbbbkwwwwkwwwwkkbbbk...',
      '........kbbbbkwwwwkwwwwbbbbk....',
      '.........kbbbkwwwwkwwwbbbbk.....',
      '..........kbwkwwwwkwwbbkkk......',
      '..........kkkkkkkkkkkkkkkk......',
    ],
    // frame 1
    [
      '................................',
      '.......k................k.......',
      '......kbk..............kbk......',
      '......kbbkk..........kkbbk......',
      '......kbbbbkkkkkkkkkkbbbbk......',
      '......kbbpbbbbwddwwwbbpbbk......',
      '......kbbppbbbwddwbbbppbbk......',
      '......kbbpbbbbwwwwwwbbpbbk......',
      '......kbbbbbwwwwwwwwwbbbbk......',
      '......kbbbbbwwwwwwwwwwwbbk......',
      '......kbwwwwwwwwwwwwwwwwbk......',
      '......kwwwwwwwwwwwwwwwwwwk......',
      '......kwwwwwwwwwwwwwwwwwwk......',
      '......kwwwkkwwwwwwwwkkwwwk......',
      '......kwwwwwwwwppwwwwwwwwk......',
      '.......kppwwwwkwwkwwwwppk.......',
      '........kwwwwwwkkwwwwwwk.k......',
      '.........kwwwwwwwwwwwwk.kbkk....',
      '..........kkwwwwwwwwkk.kbbbbk...',
      '...........kwwwwwwwwk...kbbbk...',
      '..........kwwsssssswwk...kbbk...',
      '.........kwwwwwwwwwwwwk..kbbbk..',
      '........kwwwwwwwwwwwwwwk.kbbbk..',
      '.......kwwwwwwwwwwwwwwwwkkbbbk..',
      '.......kwbbbwwwwwwwwwwwwkkbbbk..',
      '.......kbbbbbwwwwwwwwwwwkkbbk...',
      '.......kbbbbbkwwwwkwwwwwkbbbk...',
      '........kbbbbkwwwwkwwwwkkbbbk...',
      '........kbbbbkwwwwkwwwwbbbbk....',
      '.........kbbbkwwwwkwwwbbbbk.....',
      '..........kbwkwwwwkwwbbkkk......',
      '..........kkkkkkkkkkkkkkkk......',
    ],
    // frame 2
    [
      '................................',
      '.......k................k.......',
      '......kbk..............kbk......',
      '......kbbkk..........kkbbk......',
      '......kbbbbkkkkkkkkkkbbbbk......',
      '......kbbpbbbbwddwwwbbpbbk......',
      '......kbbppbbbwddwbbbppbbk......',
      '......kbbpbbbbwwwwwwbbpbbk......',
      '......kbbbbbwwwwwwwwwbbbbk......',
      '......kbbbbbwwwwwwwwwwwbbk......',
      '......kbwwwwwwwwwwwwwwwwbk......',
      '......kwwwwwwwwwwwwwwwwwwk......',
      '......kwwwkkwwwwwwwwkkwwwk......',
      '......kwwwkkwwwwwwwwkkwwwk......',
      '......kwwwwwwwwppwwwwwwwwk......',
      '.......kppwwwwkwwkwwwwppk.......',
      '........kwwwwwwkkwwwwwwk...k....',
      '.........kwwwwwwwwwwwwk...kbkk..',
      '..........kkwwwwwwwwkk...kbbbbk.',
      '...........kwwwwwwwwk.....kbbbk.',
      '..........kwwsssssswwk.....kbbk.',
      '.........kwwwwwwwwwwwwk...kbbbk.',
      '........kwwwwwwwwwwwwwwk..kbbbk.',
      '.......kwwwwwwwwwwwwwwwwk.kbbk..',
      '.......kwbbbwwwwwwwwwwwwkkbbbk..',
      '.......kbbbbbwwwwwwwwwwwkkbbbk..',
      '.......kbbbbbkwwwwkwwwwwkbbbk...',
      '........kbbbbkwwwwkwwwwkkbbbk...',
      '........kbbbbkwwwwkwwwwbbbbk....',
      '.........kbbbkwwwwkwwwbbbbk.....',
      '..........kbwkwwwwkwwbbkkk......',
      '..........kkkkkkkkkkkkkkkk......',
    ],
  ],
};
