import type { Sprite } from '../../src/cat/sprite';

// sleep_curled: 0 rest, 1 breathe in + small z, 2 second z.
// Legend: . transparent, k outline, w white, s shade, b brown, d dark brown, p pink, z sleep glyph.
export const SLEEP_CURLED: Sprite = {
  id: 'sleep_curled',
  fps: 2,
  sequence: [0, 0, 1, 1, 2, 2],
  frames: [
    // frame 0
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '.....k......k...................',
      '....kbk....kbk..................',
      '....kbbk..kbbk..................',
      '....kbpbkkbbpbk.................',
      '....kbppbbbppbkkkkkkkkkk........',
      '....kbbbbbbbbbbwbbbbbbbbkkk.....',
      '....kwwwwwwwwwwwbbbbbbbbbbbk....',
      '...kwwwwwwwwwwwwbbbbbbbbbbbwk...',
      '...kwwkwkwwkwkwwbbbbbbbbbbbwwk..',
      '...kwwwkwwwwkwwwwwwwwwwwwwwwwk..',
      '....kpwwwppwwwpwwwwwwwwwwwwwbk..',
      '....kwwwwwwwwwwwwwwwwwwwwwwbbbk.',
      '.....kkwwwwwwwwwwwwwwwwwwwbbbk..',
      '.......kkkkwwwwbbbbbbbbbbbbbk...',
      '...........kkkwbbbbbbbbbbbbk....',
      '...........kkkkkkkkkkkkkkkkk....',
    ],
    // frame 1
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '.................zzzz...........',
      '...................z............',
      '.....k......k.....z.............',
      '....kbk....kbk...zzzz...........',
      '....kbbk..kbbk..................',
      '....kbpbkkbbpbkkkkkkkkkk........',
      '....kbppbbbppbwwbbbbbbbbkk......',
      '....kbbbbbbbbbbwbbbbbbbbbbkk....',
      '....kwwwwwwwwwwwbbbbbbbbbbbwk...',
      '...kwwwwwwwwwwwwbbbbbbbbbbbwk...',
      '...kwwkwkwwkwkwwwwwwwwwwwwwwwk..',
      '...kwwwkwwwwkwwwwwwwwwwwwwwwwk..',
      '....kpwwwppwwwpwwwwwwwwwwwwwbk..',
      '....kwwwwwwwwwwwwwwwwwwwwwwbbbk.',
      '.....kkwwwwwwwwwwwwwwwwwwwbbbk..',
      '.......kkkkwwwwbbbbbbbbbbbbbk...',
      '...........kkkwbbbbbbbbbbbbk....',
      '...........kkkkkkkkkkkkkkkkk....',
    ],
    // frame 2
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '......................zzzz......',
      '........................z.......',
      '.......................z........',
      '......................zzzz......',
      '................................',
      '................................',
      '.................zzzz...........',
      '...................z............',
      '.....k......k.....z.............',
      '....kbk....kbk...zzzz...........',
      '....kbbk..kbbk..................',
      '....kbpbkkbbpbk.................',
      '....kbppbbbppbkkkkkkkkkk........',
      '....kbbbbbbbbbbwbbbbbbbbkkk.....',
      '....kwwwwwwwwwwwbbbbbbbbbbbk....',
      '...kwwwwwwwwwwwwbbbbbbbbbbbwk...',
      '...kwwkwkwwkwkwwbbbbbbbbbbbwwk..',
      '...kwwwkwwwwkwwwwwwwwwwwwwwwwk..',
      '....kpwwwppwwwpwwwwwwwwwwwwwbk..',
      '....kwwwwwwwwwwwwwwwwwwwwwwbbbk.',
      '.....kkwwwwwwwwwwwwwwwwwwwbbbk..',
      '.......kkkkwwwwbbbbbbbbbbbbbk...',
      '...........kkkwbbbbbbbbbbbbk....',
      '...........kkkkkkkkkkkkkkkkk....',
    ],
  ],
};
